@echo off
if not defined REPO_ROOT (
  for %%I in ("%~dp0..") do set "REPO_ROOT=%%~fI"
)

if not defined SAGA_MEDIA_DATA_DIR set "SAGA_MEDIA_DATA_DIR=%USERPROFILE%\saga_staff_media_data"
if not defined SAGA_MEDIA_EXPORT_DIR set "SAGA_MEDIA_EXPORT_DIR=%SAGA_MEDIA_DATA_DIR%\exports"
if not defined SAGA_MEDIA_TRANSFERS_DIR set "SAGA_MEDIA_TRANSFERS_DIR=%SAGA_MEDIA_DATA_DIR%\transfers"
if not defined SAGA_MEDIA_POLICY_SOURCES_DIR set "SAGA_MEDIA_POLICY_SOURCES_DIR=%SAGA_MEDIA_DATA_DIR%\policy_sources"
if not defined SAGA_MEDIA_SOURCES_CSV_PATH set "SAGA_MEDIA_SOURCES_CSV_PATH=%SAGA_MEDIA_DATA_DIR%\list_sources.csv"
if not defined SAGA_MEDIA_DEPARTMENT_HIERARCHY_CSV_PATH set "SAGA_MEDIA_DEPARTMENT_HIERARCHY_CSV_PATH=%SAGA_MEDIA_DATA_DIR%\department_hierarchy.csv"
if not defined SAGA_MEDIA_TRANSFER_SOURCE_INDEX_CSV_PATH set "SAGA_MEDIA_TRANSFER_SOURCE_INDEX_CSV_PATH=%SAGA_MEDIA_TRANSFERS_DIR%\source_index.csv"
if not defined SAGA_MEDIA_TRANSFER_TEMPLATE_CSV_PATH set "SAGA_MEDIA_TRANSFER_TEMPLATE_CSV_PATH=%SAGA_MEDIA_TRANSFERS_DIR%\transfer_template.csv"
if not defined SAGA_MEDIA_POLICY_SOURCE_TEMPLATE_CSV_PATH set "SAGA_MEDIA_POLICY_SOURCE_TEMPLATE_CSV_PATH=%SAGA_MEDIA_POLICY_SOURCES_DIR%\policy_source_template.csv"

if not exist "%SAGA_MEDIA_DATA_DIR%" mkdir "%SAGA_MEDIA_DATA_DIR%"
if not exist "%SAGA_MEDIA_EXPORT_DIR%" mkdir "%SAGA_MEDIA_EXPORT_DIR%"
if not exist "%SAGA_MEDIA_TRANSFERS_DIR%" mkdir "%SAGA_MEDIA_TRANSFERS_DIR%"
if not exist "%SAGA_MEDIA_POLICY_SOURCES_DIR%" mkdir "%SAGA_MEDIA_POLICY_SOURCES_DIR%"

exit /b 0
